version: "3.7"

services: 
  database_crud:
    image: postgres
    container_name: database_crud
    restart: always
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=crud
    volumes: 
      - pgdata:/data/postgres
    network_mode: host
  app:
    build: .
    container_name: crud
    volumes:
      - .:/usr/app
    network_mode: host    


volumes:
  pgdata: 
    driver: local